# Generated by Django 6.0.1 on 2026-01-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('general_category', models.CharField(blank=True, max_length=80)),
                ('specific_category', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PartColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('variant', models.CharField(blank=True, default='', max_length=50)),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('image_url_1', models.URLField(blank=True)),
                ('image_url_2', models.URLField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='parts.part')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('part', 'color_name', 'variant'), name='uniq_part_color_variant')],
            },
        ),
    ]
