# Generated by Django 6.0.1 on 2026-01-13 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lego_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex', models.CharField(blank=True, default='', max_length=7)),
                ('is_transparent', models.BooleanField(default=False)),
                ('is_metallic', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='partcolor',
            name='uniq_part_color_variant',
        ),
        migrations.AddField(
            model_name='part',
            name='image_url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partcolor',
            name='image_url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partcolor',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partcolor',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_colors', to='parts.color'),
        ),
        migrations.AddConstraint(
            model_name='partcolor',
            constraint=models.UniqueConstraint(fields=('part', 'color', 'variant'), name='uniq_part_color_variant'),
        ),
        migrations.RemoveField(
            model_name='partcolor',
            name='color_name',
        ),
    ]
