# Generated by Django 6.0.1 on 2026-01-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_color_remove_partcolor_uniq_part_color_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="part",
            name="image_url_1",
            field=models.URLField(blank=True, null=True),
        ),
    ]
