# Generated by Django 6.0.1 on 2026-01-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_color_remove_partcolor_uniq_part_color_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partcolor',
            name='color_name',
        ),
    ]
