# Generated by Django 6.0.1 on 2026-01-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_color_remove_partcolor_color_name_partcolor_color'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partcolor',
        ),
        migrations.AddField(
            model_name='part',
            name='image_url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='partcolor',
            constraint=models.UniqueConstraint(fields=('part', 'color', 'variant'), name='uniq_part_color_variant'),
        ),
    ]
