# Generated by Django 6.0.1 on 2026-01-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_as_top_by', to='sets.theme'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_themes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='sets.theme'),
        ),
    ]
