# Generated by Django 6.0.1 on 2026-01-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('set_name', models.CharField(max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('piece_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('part_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.partcolor')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.set')),
            ],
            options={
                'unique_together': {('set', 'part_color')},
            },
        ),
        migrations.AddField(
            model_name='set',
            name='parts',
            field=models.ManyToManyField(related_name='sets', through='sets.SetPart', to='parts.partcolor'),
        ),
        migrations.AddField(
            model_name='set',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='sets.theme'),
        ),
    ]
